a = input("Masukkan daftar belanja 1: ")
b = input("Masukkan daftar belanja 2: ")
c = input("Tambahkan data ke daftar belanja 1: ")
d = input("Tambahkan data ke daftar belanja 2: ")
print("Daftar belanja 1 adalah ", str(a),",",str(c))
print("Daftar belanja 2 adalah ", str(b),",",str(d))
